#!/bin/bash
#chkconfig:12345 80 05
#description:php-fpm Service
# php-fpm管理脚本
# @author lizhibin
# @date 2018-08-17
# @mail 331313869@qq.com

#config
php-fpm=/usr/local/php-7.2.4/sbin/php-fpm
php-fpm_pid=/usr/local/php-7.2.4/var/run/php-fpm.pid

pid=0
if [ -f $php-fpm_pid ]
then
    pid=$(cat $php-fpm_pid)
fi

status() {
    if [ $pid -gt 0 ]
    then
        return 1
    else
        return 0
    fi
}

start() {
    status
    if [ $? -gt 0 ]
    then
        echo "Php-fpm is running!"
    else
        echo "Starting php-fpm..."
        `$php-fpm`
    fi
}

stop() {
    status
    if [ $? -gt 0 ]
    then
        echo "Stopping php-fpm..."
        `kill $pid`
    else
        echo "Php-fpm is not running!"
    fi
}
reload() {
    status
    if [ $? -eq 1 ]
    then
        echo "Reloading php-fpm..."
        `kill -USR2 $pid`
    else
        echo "Php-fpm is not running!"
    fi
}

case "$1" in
    start)
        start
    ;;
    status)
        status
        echo php-fpm is running:$?
    ;;
    stop)
        stop
    ;;
    reload)
        reload
    ;;
    *)
        echo $"Usage: php-fpm {start|stop|reload|status}"
        RETVAL=2
esac

exit $RETVAL
